// Copyright Notice ===========================================================
//
// ising.h, Copyright (c) 2023 Aingeru Ramos
//
// All Rights Reserved ========================================================
//
// This file is part of MCMC_C software project.
//
// MCMC_C is propietary software. The author has all the rights to the work.
// No third party may make use of this work without explicit permission of the author.
//
// ============================================================================

#ifndef _ISING_H_
#define _ISING_H_

#include "constants.h"
#include "stack.h"

/**
 * @class SpinGlassIterationResult
 * @param _energy Energy of the model
 * @param _averasge_spin Average spin of the model
 * @brief
 * * Instances of this class saves the state generated 
 * * by one iteration of the MCMC
*/
class SpinGlassIterationResult {
    public:
        double _energy;
        int _average_spin;

        /**
         * @name SpinGlassIterationResult
         * @remark constructor
        */
        _CUDA_DECOR_ SpinGlassIterationResult();

        /**
         * @name SpinGlassIterationResult
         * @overload
         * @param energy Energy of the model
         * @param average_spin Average spin of the model
        */
        _CUDA_DECOR_ SpinGlassIterationResult(double energy, double average_spin);

        /**
         * @name copy
         * @return Copy of this SpinGlassIterationResult
         * @brief
         * * Creates a copy of this SpinGlassIterationResult
        */
        _CUDA_DECOR_ SpinGlassIterationResult* copy();
};

/**
 * @class SpinGlass
 * @param _kernel_cross Convolution kernel in cross shape
 * @param _kernel_semicross Convolution kernel in semi-cross shape (Bottom and Right)
 * @param _sample State of the SpinGlass
 * @param _last_delta The last delta calculated with 'delta()'
 * @param _last_spin The value of the spin moved in the trial
 * @param _results Stack of iteration results
 * @brief
 * * Instances of this class represent a replica in
 * * the MCMC algorithm. Specifically, this replica
 * * has the behaviour of a SpinGlass
*/
class SpinGlass {
    public:
        int _kernel_cross[9];
        int _kernel_semicross[9];

        char _sample[N_ROW*N_COL];

        double _last_delta;
        char _last_spin;
        
        Stack<SpinGlassIterationResult*, N_ITERATIONS> _results;

        /**
         * @name init
         * @brief
         * * Initializes the replica
        */
        _CUDA_DECOR_ void init();

        /**
         * @name trial
         * @return A trial
         * @brief
         * * Generates a trial of the replica
        */
        _CUDA_DECOR_ void* trial();

        /**
         * @name delta
         * @param trial A trial generated by 'trial()'
         * @return Value of the difference of the actual state of the replica and 
         * the replica result of applying the trial
         * @brief
         * * Calculates the effect of acceptance of the trial
        */
        _CUDA_DECOR_ double delta(void* trial);

        /**
         * @name move
         * @param trial A trial generated by 'trial()'
         * @brief
         * * Applies the trial to the replica
        */
        _CUDA_DECOR_ void move(void* trial);

        /**
         * @name save
         * @param trial A trial generated by 'trial()'
         * @brief
         * * Save the state of the replica
        */
        _CUDA_DECOR_ void save(void* trial);
};

/**
 * @name is_index_in_matrix
 * @param mat Matrix to use
 * @param n_row Number of rows of the matrix
 * @param n_col Number of collumns of the matrix
 * @param row Row of the index to check
 * @param col Collumn of the index to check
 * @return A value indicating if the index is inside 
 * the matrix boundaries
 * @brief
 * * Return 1 if index is inside the matrix, else 0
*/
_CUDA_DECOR_ int is_index_in_matrix(char* mat, int n_row, int n_col, int row, int col);

/**
 * @name single_convolve
 * @param mat Matrix to use
 * @param n_row Number of rows of the matrix
 * @param n_col Number of collumns of the matrix
 * @param index Index of the matrix where do the convolution
 * @param kernel Kernel of the convolution
 * @param kernel_size Size of the kernel
 * @return The value of the convolution
 * @brief
 * * Applies the kernel in the specified position of the matrix
 * @note
 * The kernel size is assumed to be (kernel_size x kernel_size). 
 * Those values that, when applying the kernel, are outside the matrix, it will assumed the value 0 
*/
_CUDA_DECOR_ int apply_kernel(char* mat, int n_row, int n_col, int index, int* kernel, int kernel_size);

#endif